import { Action, ActionContext } from './Action';
import axios from 'axios';
import { decryptObject } from '../../utils/encryption';

export class GitHubPullRequestAction implements Action {
  id = 'action_github_pr';

  async execute(config: any, context: ActionContext): Promise<any> {
    const { repo, branch, baseBranch = 'main', title, body, files } = config;
    
    if (!repo || !branch || !title || !files || !Array.isArray(files)) {
      throw new Error('Missing required GitHub PR fields (repo, branch, title, files)');
    }

    if (!context.workspaceId || !context.supabase) {
      throw new Error('Missing workspace context for execution');
    }

    // 1. Fetch connected GitHub system
    const { data: systems, error: sysErr } = await context.supabase
       .from('company_systems')
       .select('*')
       .eq('workspace_id', context.workspaceId)
       .eq('status', 'CONNECTED');

    if (sysErr || !systems || systems.length === 0) {
       return { success: false, error: { message: 'No active connections found for this workspace.' } };
    }

    const githubSys = systems.find(s => s.system_type === 'GITHUB');
    
    if (!githubSys) {
       return { success: false, error: { message: 'GitHub is not connected. Please authorize Source Control in Connections.' } };
    }

    // 2. Decrypt credentials
    let credentials: any = {};
    try {
       credentials = decryptObject(githubSys.connection_id);
    } catch (e) {
       return { success: false, error: { message: 'Failed to decrypt GitHub credentials.' } };
    }

    const token = credentials.apiKey;
    if (!token) {
      return { success: false, error: { message: 'GitHub API Token is missing from connection.' } };
    }

    try {
      const api = axios.create({
        baseURL: 'https://api.github.com',
        headers: {
          'Authorization': `token ${token}`,
          'Accept': 'application/vnd.github.v3+json'
        }
      });

      // Step 1: Get the SHA of the base branch
      const refRes = await api.get(`/repos/${repo}/git/refs/heads/${baseBranch}`);
      const baseSha = refRes.data.object.sha;

      // Step 2: Create a new branch (ref) from the base SHA
      try {
        await api.post(`/repos/${repo}/git/refs`, {
          ref: `refs/heads/${branch}`,
          sha: baseSha
        });
      } catch (err: any) {
        // If branch already exists, that's okay (or we could handle it), but let's assume it fails if it exists
        if (err.response?.status !== 422) throw err; 
      }

      // Step 3: Create a tree with the new files
      const tree = files.map((file: any) => ({
        path: file.path,
        mode: '100644', // file (blob)
        type: 'blob',
        content: file.content
      }));

      const treeRes = await api.post(`/repos/${repo}/git/trees`, {
        base_tree: baseSha,
        tree: tree
      });
      const newTreeSha = treeRes.data.sha;

      // Step 4: Create a commit
      const commitRes = await api.post(`/repos/${repo}/git/commits`, {
        message: title,
        tree: newTreeSha,
        parents: [baseSha]
      });
      const newCommitSha = commitRes.data.sha;

      // Step 5: Update the branch reference to point to the new commit
      await api.patch(`/repos/${repo}/git/refs/heads/${branch}`, {
        sha: newCommitSha,
        force: true
      });

      // Step 6: Create the Pull Request
      const prRes = await api.post(`/repos/${repo}/pulls`, {
        title: title,
        body: body || 'Automated PR generated by ItWield AI CTO.',
        head: branch,
        base: baseBranch
      });

      return {
          success: true,
          provider: 'GITHUB',
          action: 'PULL_REQUEST_CREATED',
          repo,
          branch,
          prUrl: prRes.data.html_url,
          prNumber: prRes.data.number,
          message: `Successfully created PR #${prRes.data.number}: ${title}`
      };

    } catch (error: any) {
      console.error('GitHub API Error:', error.response?.data || error.message);
      return {
        success: false,
        error: {
          code: 'GITHUB_API_ERROR',
          message: error.response?.data?.message || error.message || 'Failed to interact with GitHub API'
        }
      };
    }
  }
}
