ALTER TABLE tasks ADD COLUMN IF NOT EXISTS reviewed_by_cmo BOOLEAN DEFAULT FALSE;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS cmo_locked_until TIMESTAMPTZ;
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS cmo_status TEXT DEFAULT 'IDLE';
